### ISSUE TITLE
About graphics card

### ISSUE THREAD

**Issue by ChenCherry** [Kali-Hac/Locality-Awareness-SGE#3]
Can you provide how number of graphics card you need, and about the type (Nvidia Geforce 2080Ti or NVIDIA Tesla P100 or others)?

**Comment by Kali-Hac** [comment]
The whole model is implemented by Tensorflow v1.9 and trained on the NVIDIA TITAN V (our graphics card) and Intel(R) Xeon(R) E5-2690 CPUs of our machine. Specifically, it needs 1064 MB for training the gait encoding model and 616 MB  for the recognition network model. Since our graphics card possesses 11.78GB, we only need one card to train and test. We believe that it is the same for other cards like NVIDIA GeForce 2080Ti or NVIDIA Tesla P100. Thank you.
